


#rbenv

if [ -d $HOME/.rbenv/bin ] ; then
export PATH="$HOME/.rbenv/bin:$HOME/.rbenv/shims:$PATH"
eval "$(rbenv init -)"
fi

alias la='ls -la'
alias ll='ls -l'
alias nave=$HOME/opt/nave/nave.sh
alias g=git


if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
