
#PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

autoload -U compinit
compinit

export EDITOR=vim

alias ll='ls -l'
alias gg='git lga'
alias be='bundle exec'

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"
