
set nocompatible
filetype off

"NeoBundle

if has('vim_starting')
  set runtimepath+=~/dotfiles/vim/vimfiles/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/dotfiles/vim/vimfiles/bundle/'))

NeoBundle "rails.vim"
NeoBundle "Tagbar"

filetype plugin indent on

"====================================

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
