
set nocompatible
filetype off

"NeoBundle

if has('vim_starting')
  set runtimepath+=~/dotfiles/vim/vimfiles/bundle/neobundle.vim/
endif

call neobundle#rc(expand('~/dotfiles/vim/vimfiles/bundle/'))

NeoBundle "Shougo/unite.vim.git"
NeoBundle "Shougo/vimfiler"
NeoBundle "Shougo/vimshell"
NeoBundle 'Shougo/neosnippet'
NeoBundle 'Shougo/neosnippet'
NeoBundle 'Shougo/neocomplcache.vim'

NeoBundle 'Shougo/vimproc', {
      \ 'build' : {
      \     'windows' : 'make -f make_mingw32.mak',
      \     'cygwin' : 'make -f make_cygwin.mak',
      \     'mac' : 'make -f make_mac.mak',
      \     'unix' : 'make -f make_unix.mak',
      \    },
      \ }
NeoBundle 'Lokaltog/powerline', { 'rtp' : 'powerline/bindings/vim'}
NeoBundle "rails.vim"
NeoBundle "Tagbar"
NeoBundle "scrooloose/nerdtree"
NeoBundle "scrooloose/nerdcommenter"
"NeoBundle "kien/ctrlp.vim"
nnoremap <C-p> :Unite file_rec/async<cr>
NeoBundle "tpope/vim-fugitive"

NeoBundle 'w0ng/vim-hybrid'
NeoBundle 'jpo/vim-railscasts-theme'

NeoBundle 'tpope/vim-surround'
NeoBundle 'nathanaelkane/vim-indent-guides'


filetype plugin indent on

"====================================

set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set t_Co=256

syntax on

set laststatus=2

"unite.vim
"バッファ一覧
nnoremap <silent> ,ub :<C-u>Unite buffer<CR>
"ファイル一覧
nnoremap <silent> ,uf :<C-u>UniteWithBufferDir -buffer-name=files file<CR>
"レジスタ一覧
nnoremap <silent> ,ur :<C-u>Unite -buffer-name=register register<CR>
"最近使用したファイル一覧
nnoremap <silent> ,um :<C-u>Unite file_mru<CR>

nnoremap <silent> ,uu :<C-u>Unite buffer file_mru<CR>
nnoremap <silent> ,ua :<C-u>UniteWithBufferDir -buffer-name=files buffer file_mru bookmark file<CR>

"NERDCommenter
map ,, <Plug>NERDCommenterToggle
